sonar.projectKey=com.ethos.frontend
sonar.projectName=EthosPlatform Frontend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info