@startuml C3-Component-Diagram-app

/' Importar Paquetes '/
!include %getenv("PLANTUML_C4_HOME")/C4_Component.puml

/' Definir Iconos y Fuentes '/
!define DEVICONS %getenv("PLANTUML_ICON_FONT_SPRITES")/icons/devicons
!define FONTAWESOME %getenv("PLANTUML_ICON_FONT_SPRITES")/icons/font-awesome-5

left to right direction

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

Container(web_app_app , "EthosPlatform Web App - App" , "React / Vite" , "Punto de entrada global de la aplicación, se encarga de coordinar toda la aplicación.")
Container_Boundary(web_app_app_boundary , "EthosPlatform Web App - App"){
    Component(router , "Router" , "React" , "Define la navegación global y rutas protegidas.")
    Component(store , "Store" , "React" , "Estado global de la aplicación, es informacion utilizada por muchas partes del sistema.")
    Component(styles , "Styles" , "React" , "Contiene estilos globales, CSS, variables CSS, temas, etc.")
    Component(app_tsx , "App.tsx" , "React" , "Contenedor central donde se agrupan y organizan los demás componentes de la interfaz de usuario, antes de ser renderizados en la pantalla, es invocado usualmente por el archivo de inicio main.tsx.")
}

web_app_app ..> web_app_app_boundary

Rel(app_tsx , router , "Usa Rutas")
Rel(app_tsx , store , "Usa")
Rel(app_tsx , styles , "Usa")

@enduml