@startuml C1-System-Context-Diagram
/' Importar Paquetes '/
!include ../../../../Packages/C4-PlantUML/C4_Context.puml

/' Definir Iconos y Fuentes '/
!define DEVICONS ../../../../Packages/plantuml-icon-font-sprites/icons/devicons
!define FONTAWESOME ../../../../Packages/plantuml-icon-font-sprites/icons/font-awesome-5

!include DEVICONS/postgresql.puml
!include DEVICONS/nodejs.puml

/' Definir Fuentes '/
!include FONTAWESOME/users.puml

left to right direction

LAYOUT_WITH_LEGEND()

Person(user_1 , "Usuario" , "Comparte sus experiencias relacionadas con reflexiones éticas y morales e interactúa con la aplicación.")
Person(admin_1 , "Administrador" , "Gestiona los usuarios, la aplicación y el contenido.")

System(ethosplatform , "EthosPlatform" , "Sistema web comunitaria para compartir experiencias personales estructuradas relacionadas con reflexiones éticas y morales." , $sprite="nodejs")

System_Ext(dbpostgresql , "PostgreSQL" , "Sistema Gestor de Base de Datos." , $sprite="postgresql")

Rel(user_1 , ethosplatform , "Usa")
Rel(admin_1 , ethosplatform , "Administra")

Rel(ethosplatform , dbpostgresql , "Almacena y lee información")

@enduml